### ISSUE TITLE
依赖库

### ISSUE THREAD

**Issue by junjun2712** [cksgf/ServerManagement#1]
有没有 安装版本的清单 或者怎么联系你

**Comment by cksgf** [comment]
你好，可以加我qq，2986715422

**Comment by cksgf** [comment]
运行需要python3.6以上的环境，需其中用到了flask，psutil，datetime，paramiko，chardet，requests，我也忘了那些是需要自行安装的了，你检查下，我晚上会添加一个安装清单 = =，你不说我还真没注意这个

**Comment by cksgf** [comment]
增加了requirements.txt,直接在目录下 pip -r install requirements.txt即可
