### ISSUE TITLE
启动服务时报错

### ISSUE THREAD

**Issue by jianjiefang** [cksgf/ServerManagement#5]
在运行项目时报了这个错。
cannot import name 'app' from 'index'
![image](https://user-images.githubusercontent.com/42630557/56331443-d8c54c00-61be-11e9-87bb-afb514bc9718.png)

**Comment by cksgf** [comment]
> 在运行项目时报了这个错。
> cannot import name 'app' from 'index'
> ![image](https://user-images.githubusercontent.com/42630557/56331443-d8c54c00-61be-11e9-87bb-afb514bc9718.png)
程序入口文件名index,不要改名字,,,如果非要改的话记得把里面引用的名字都改一下
