### ISSUE TITLE
部署到linux报错

### ISSUE THREAD

**Issue by steven-xgt** [cksgf/ServerManagement#8]
使用uwsgi+nginx部署到linux服务器的时候报错：
![image](https://user-images.githubusercontent.com/29575784/58382582-a0efc680-7ffe-11e9-892d-713963eba613.png)

**Comment by cksgf** [comment]
> 使用uwsgi+nginx部署到linux服务器的时候报错：
> ![image](https://user-images.githubusercontent.com/29575784/58382582-a0efc680-7ffe-11e9-892d-713963eba613.png)

改成小写就行。

**Comment by steven-xgt** [comment]
就是小写不行，我改成大写尝试的，应该不是大小写的问题，python index.py正常起没有问题，但是uwsgi起的时候会报错，命令如下：uwsgi --http :5000 --wsgi-file index.py  --callable=app --chdir=/opt/ServerManagement  -H /opt/ServerManagement/env

**Comment by cksgf** [comment]
> 就是小写不行，我改成大写尝试的，应该不是大小写的问题，python index.py正常起没有问题，但是uwsgi起的时候会报错，命令如下：uwsgi --http :5000 --wsgi-file index.py --callable=app --chdir=/opt/ServerManagement -H /opt/ServerManagement/env

那要不然改成 return render_template('login.html')应该也可以

**Comment by steven-xgt** [comment]
是uwsgi的问题，使用blueprint可以解决问题

**Comment by cksgf** [comment]
> 是uwsgi的问题，使用blueprint可以解决问题

好的
