### ISSUE TITLE
文件权限存在bug

### ISSUE THREAD

**Issue by Ddosser** [cksgf/ServerManagement#9]
修改文件权限时，一般情况下都是输入(777,666)等文件权限位，但这应该是用的8进制，后台用int进行转换变成了１０进制，输入777后权限变成了411，因此需要把route/file.py第１５８行改为：
os.chmod(fileName,int(power, 8))，这样就可以达到预期权限。

**Comment by cksgf** [comment]
> 修改文件权限时，一般情况下都是输入(777,666)等文件权限位，但这应该是用的8进制，后台用int进行转换变成了１０进制，输入777后权限变成了411，因此需要把route/file.py第１５８行改为：
> os.chmod(fileName,int(power, 8))，这样就可以达到预期权限。

感谢指正，已修改^_^
